@isTest
public class documentpagecontroller_Test{
    public static testmethod void methodname(){
      /*  Program__c pro=new program__c();
        pro.Name='EMBA-UK-London';
        insert pro;
           
        Contact con=New Contact();
        con.LastName='Test';
        con.Program_Primary__c=pro.id;
        con.Applicant_Email__c='test@test2test.com';
        Insert Con;
        
        Rotation__c rt=new Rotation__c();
        rt.Name=con.Name;
        rt.Student__c=con.id;
        rt.Type__c='Mod E';
        Insert rt;
        
        Rotation_Documents__c rd=new Rotation_Documents__c();
        rd.Name='test';
        rd.Rotation1__c=rt.id;
        insert rd;
        
        ApexPages.CurrentPage().getParameters().put('id',rt.id);
        documentpagecontroller dp=new documentpagecontroller();
        dp.getrotdocs();
        dp.dispdocs();
        dp.getclist();
        dp.saveand();
        */
        
    }
}